using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace BAS.Concept.File.Upload.Client
{
    // WARNING: Essa classe foi gerada automaticamente por um template T4. NÃO modifique manualmente.
    public class ContentTypeMap
    {
        private const string DEFAULT_MIMETYPE = "application/unknown";

        private static Lazy<Dictionary<string, string[]>> _mimeTypes = new Lazy<Dictionary<string, string[]>>(
            () => new Dictionary<string, string[]>
            {
                // A lista a baixo foi gerada com base na publicação de MIME Types da Apache
                // http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types

				{ "application/andrew-inset", new []{ "ez" } },
				{ "application/applixware", new []{ "aw" } },
				{ "application/atom+xml", new []{ "atom" } },
				{ "application/atomcat+xml", new []{ "atomcat" } },
				{ "application/atomsvc+xml", new []{ "atomsvc" } },
				{ "application/ccxml+xml", new []{ "ccxml" } },
				{ "application/cdmi-capability", new []{ "cdmia" } },
				{ "application/cdmi-container", new []{ "cdmic" } },
				{ "application/cdmi-domain", new []{ "cdmid" } },
				{ "application/cdmi-object", new []{ "cdmio" } },
				{ "application/cdmi-queue", new []{ "cdmiq" } },
				{ "application/cu-seeme", new []{ "cu" } },
				{ "application/davmount+xml", new []{ "davmount" } },
				{ "application/docbook+xml", new []{ "dbk" } },
				{ "application/dssc+der", new []{ "dssc" } },
				{ "application/dssc+xml", new []{ "xdssc" } },
				{ "application/ecmascript", new []{ "ecma" } },
				{ "application/emma+xml", new []{ "emma" } },
				{ "application/epub+zip", new []{ "epub" } },
				{ "application/exi", new []{ "exi" } },
				{ "application/font-tdpfr", new []{ "pfr" } },
				{ "application/gml+xml", new []{ "gml" } },
				{ "application/gpx+xml", new []{ "gpx" } },
				{ "application/gxf", new []{ "gxf" } },
				{ "application/hyperstudio", new []{ "stk" } },
				{ "application/inkml+xml", new []{ "ink", "inkml" } },
				{ "application/ipfix", new []{ "ipfix" } },
				{ "application/java-archive", new []{ "jar" } },
				{ "application/java-serialized-object", new []{ "ser" } },
				{ "application/java-vm", new []{ "class" } },
				{ "application/javascript", new []{ "js" } },
				{ "application/json", new []{ "json" } },
				{ "application/jsonml+json", new []{ "jsonml" } },
				{ "application/lost+xml", new []{ "lostxml" } },
				{ "application/mac-binhex40", new []{ "hqx" } },
				{ "application/mac-compactpro", new []{ "cpt" } },
				{ "application/mads+xml", new []{ "mads" } },
				{ "application/marc", new []{ "mrc" } },
				{ "application/marcxml+xml", new []{ "mrcx" } },
				{ "application/mathematica", new []{ "ma", "nb", "mb" } },
				{ "application/mathml+xml", new []{ "mathml" } },
				{ "application/mbox", new []{ "mbox" } },
				{ "application/mediaservercontrol+xml", new []{ "mscml" } },
				{ "application/metalink+xml", new []{ "metalink" } },
				{ "application/metalink4+xml", new []{ "meta4" } },
				{ "application/mets+xml", new []{ "mets" } },
				{ "application/mods+xml", new []{ "mods" } },
				{ "application/mp21", new []{ "m21", "mp21" } },
				{ "application/mp4", new []{ "mp4s" } },
				{ "application/msword", new []{ "doc", "dot" } },
				{ "application/mxf", new []{ "mxf" } },
				{ "application/octet-stream", new []{ "bin", "dms", "lrf", "mar", "so", "dist", "distz", "pkg", "bpk", "dump", "elc", "deploy" } },
				{ "application/oda", new []{ "oda" } },
				{ "application/oebps-package+xml", new []{ "opf" } },
				{ "application/ogg", new []{ "ogx" } },
				{ "application/omdoc+xml", new []{ "omdoc" } },
				{ "application/onenote", new []{ "onetoc", "onetoc2", "onetmp", "onepkg" } },
				{ "application/oxps", new []{ "oxps" } },
				{ "application/patch-ops-error+xml", new []{ "xer" } },
				{ "application/pdf", new []{ "pdf" } },
				{ "application/pgp-encrypted", new []{ "pgp" } },
				{ "application/pgp-signature", new []{ "asc", "sig" } },
				{ "application/pics-rules", new []{ "prf" } },
				{ "application/pkcs10", new []{ "p10" } },
				{ "application/pkcs7-mime", new []{ "p7m", "p7c" } },
				{ "application/pkcs7-signature", new []{ "p7s" } },
				{ "application/pkcs8", new []{ "p8" } },
				{ "application/pkix-attr-cert", new []{ "ac" } },
				{ "application/pkix-cert", new []{ "cer" } },
				{ "application/pkix-crl", new []{ "crl" } },
				{ "application/pkix-pkipath", new []{ "pkipath" } },
				{ "application/pkixcmp", new []{ "pki" } },
				{ "application/pls+xml", new []{ "pls" } },
				{ "application/postscript", new []{ "ai", "eps", "ps" } },
				{ "application/prs.cww", new []{ "cww" } },
				{ "application/pskc+xml", new []{ "pskcxml" } },
				{ "application/rdf+xml", new []{ "rdf" } },
				{ "application/reginfo+xml", new []{ "rif" } },
				{ "application/relax-ng-compact-syntax", new []{ "rnc" } },
				{ "application/resource-lists+xml", new []{ "rl" } },
				{ "application/resource-lists-diff+xml", new []{ "rld" } },
				{ "application/rls-services+xml", new []{ "rs" } },
				{ "application/rpki-ghostbusters", new []{ "gbr" } },
				{ "application/rpki-manifest", new []{ "mft" } },
				{ "application/rpki-roa", new []{ "roa" } },
				{ "application/rsd+xml", new []{ "rsd" } },
				{ "application/rss+xml", new []{ "rss" } },
				{ "application/rtf", new []{ "rtf" } },
				{ "application/sbml+xml", new []{ "sbml" } },
				{ "application/scvp-cv-request", new []{ "scq" } },
				{ "application/scvp-cv-response", new []{ "scs" } },
				{ "application/scvp-vp-request", new []{ "spq" } },
				{ "application/scvp-vp-response", new []{ "spp" } },
				{ "application/sdp", new []{ "sdp" } },
				{ "application/set-payment-initiation", new []{ "setpay" } },
				{ "application/set-registration-initiation", new []{ "setreg" } },
				{ "application/shf+xml", new []{ "shf" } },
				{ "application/smil+xml", new []{ "smi", "smil" } },
				{ "application/sparql-query", new []{ "rq" } },
				{ "application/sparql-results+xml", new []{ "srx" } },
				{ "application/srgs", new []{ "gram" } },
				{ "application/srgs+xml", new []{ "grxml" } },
				{ "application/sru+xml", new []{ "sru" } },
				{ "application/ssdl+xml", new []{ "ssdl" } },
				{ "application/ssml+xml", new []{ "ssml" } },
				{ "application/tei+xml", new []{ "tei", "teicorpus" } },
				{ "application/thraud+xml", new []{ "tfi" } },
				{ "application/timestamped-data", new []{ "tsd" } },
				{ "application/vnd.3gpp.pic-bw-large", new []{ "plb" } },
				{ "application/vnd.3gpp.pic-bw-small", new []{ "psb" } },
				{ "application/vnd.3gpp.pic-bw-var", new []{ "pvb" } },
				{ "application/vnd.3gpp2.tcap", new []{ "tcap" } },
				{ "application/vnd.3m.post-it-notes", new []{ "pwn" } },
				{ "application/vnd.accpac.simply.aso", new []{ "aso" } },
				{ "application/vnd.accpac.simply.imp", new []{ "imp" } },
				{ "application/vnd.acucobol", new []{ "acu" } },
				{ "application/vnd.acucorp", new []{ "atc", "acutc" } },
				{ "application/vnd.adobe.air-application-installer-package+zip", new []{ "air" } },
				{ "application/vnd.adobe.formscentral.fcdt", new []{ "fcdt" } },
				{ "application/vnd.adobe.fxp", new []{ "fxp", "fxpl" } },
				{ "application/vnd.adobe.xdp+xml", new []{ "xdp" } },
				{ "application/vnd.adobe.xfdf", new []{ "xfdf" } },
				{ "application/vnd.ahead.space", new []{ "ahead" } },
				{ "application/vnd.airzip.filesecure.azf", new []{ "azf" } },
				{ "application/vnd.airzip.filesecure.azs", new []{ "azs" } },
				{ "application/vnd.amazon.ebook", new []{ "azw" } },
				{ "application/vnd.americandynamics.acc", new []{ "acc" } },
				{ "application/vnd.amiga.ami", new []{ "ami" } },
				{ "application/vnd.android.package-archive", new []{ "apk" } },
				{ "application/vnd.anser-web-certificate-issue-initiation", new []{ "cii" } },
				{ "application/vnd.anser-web-funds-transfer-initiation", new []{ "fti" } },
				{ "application/vnd.antix.game-component", new []{ "atx" } },
				{ "application/vnd.apple.installer+xml", new []{ "mpkg" } },
				{ "application/vnd.apple.mpegurl", new []{ "m3u8" } },
				{ "application/vnd.aristanetworks.swi", new []{ "swi" } },
				{ "application/vnd.astraea-software.iota", new []{ "iota" } },
				{ "application/vnd.audiograph", new []{ "aep" } },
				{ "application/vnd.blueice.multipass", new []{ "mpm" } },
				{ "application/vnd.bmi", new []{ "bmi" } },
				{ "application/vnd.businessobjects", new []{ "rep" } },
				{ "application/vnd.chemdraw+xml", new []{ "cdxml" } },
				{ "application/vnd.chipnuts.karaoke-mmd", new []{ "mmd" } },
				{ "application/vnd.cinderella", new []{ "cdy" } },
				{ "application/vnd.claymore", new []{ "cla" } },
				{ "application/vnd.cloanto.rp9", new []{ "rp9" } },
				{ "application/vnd.clonk.c4group", new []{ "c4g", "c4d", "c4f", "c4p", "c4u" } },
				{ "application/vnd.cluetrust.cartomobile-config", new []{ "c11amc" } },
				{ "application/vnd.cluetrust.cartomobile-config-pkg", new []{ "c11amz" } },
				{ "application/vnd.commonspace", new []{ "csp" } },
				{ "application/vnd.contact.cmsg", new []{ "cdbcmsg" } },
				{ "application/vnd.cosmocaller", new []{ "cmc" } },
				{ "application/vnd.crick.clicker", new []{ "clkx" } },
				{ "application/vnd.crick.clicker.keyboard", new []{ "clkk" } },
				{ "application/vnd.crick.clicker.palette", new []{ "clkp" } },
				{ "application/vnd.crick.clicker.template", new []{ "clkt" } },
				{ "application/vnd.crick.clicker.wordbank", new []{ "clkw" } },
				{ "application/vnd.criticaltools.wbs+xml", new []{ "wbs" } },
				{ "application/vnd.ctc-posml", new []{ "pml" } },
				{ "application/vnd.cups-ppd", new []{ "ppd" } },
				{ "application/vnd.curl.car", new []{ "car" } },
				{ "application/vnd.curl.pcurl", new []{ "pcurl" } },
				{ "application/vnd.dart", new []{ "dart" } },
				{ "application/vnd.data-vision.rdz", new []{ "rdz" } },
				{ "application/vnd.dece.data", new []{ "uvf", "uvvf", "uvd", "uvvd" } },
				{ "application/vnd.dece.ttml+xml", new []{ "uvt", "uvvt" } },
				{ "application/vnd.dece.unspecified", new []{ "uvx", "uvvx" } },
				{ "application/vnd.dece.zip", new []{ "uvz", "uvvz" } },
				{ "application/vnd.denovo.fcselayout-link", new []{ "fe_launch" } },
				{ "application/vnd.dna", new []{ "dna" } },
				{ "application/vnd.dolby.mlp", new []{ "mlp" } },
				{ "application/vnd.dpgraph", new []{ "dpg" } },
				{ "application/vnd.dreamfactory", new []{ "dfac" } },
				{ "application/vnd.ds-keypoint", new []{ "kpxx" } },
				{ "application/vnd.dvb.ait", new []{ "ait" } },
				{ "application/vnd.dvb.service", new []{ "svc" } },
				{ "application/vnd.dynageo", new []{ "geo" } },
				{ "application/vnd.ecowin.chart", new []{ "mag" } },
				{ "application/vnd.enliven", new []{ "nml" } },
				{ "application/vnd.epson.esf", new []{ "esf" } },
				{ "application/vnd.epson.msf", new []{ "msf" } },
				{ "application/vnd.epson.quickanime", new []{ "qam" } },
				{ "application/vnd.epson.salt", new []{ "slt" } },
				{ "application/vnd.epson.ssf", new []{ "ssf" } },
				{ "application/vnd.eszigno3+xml", new []{ "es3", "et3" } },
				{ "application/vnd.ezpix-album", new []{ "ez2" } },
				{ "application/vnd.ezpix-package", new []{ "ez3" } },
				{ "application/vnd.fdf", new []{ "fdf" } },
				{ "application/vnd.fdsn.mseed", new []{ "mseed" } },
				{ "application/vnd.fdsn.seed", new []{ "seed", "dataless" } },
				{ "application/vnd.flographit", new []{ "gph" } },
				{ "application/vnd.fluxtime.clip", new []{ "ftc" } },
				{ "application/vnd.framemaker", new []{ "fm", "frame", "maker", "book" } },
				{ "application/vnd.frogans.fnc", new []{ "fnc" } },
				{ "application/vnd.frogans.ltf", new []{ "ltf" } },
				{ "application/vnd.fsc.weblaunch", new []{ "fsc" } },
				{ "application/vnd.fujitsu.oasys", new []{ "oas" } },
				{ "application/vnd.fujitsu.oasys2", new []{ "oa2" } },
				{ "application/vnd.fujitsu.oasys3", new []{ "oa3" } },
				{ "application/vnd.fujitsu.oasysgp", new []{ "fg5" } },
				{ "application/vnd.fujitsu.oasysprs", new []{ "bh2" } },
				{ "application/vnd.fujixerox.ddd", new []{ "ddd" } },
				{ "application/vnd.fujixerox.docuworks", new []{ "xdw" } },
				{ "application/vnd.fujixerox.docuworks.binder", new []{ "xbd" } },
				{ "application/vnd.fuzzysheet", new []{ "fzs" } },
				{ "application/vnd.genomatix.tuxedo", new []{ "txd" } },
				{ "application/vnd.geogebra.file", new []{ "ggb" } },
				{ "application/vnd.geogebra.tool", new []{ "ggt" } },
				{ "application/vnd.geometry-explorer", new []{ "gex", "gre" } },
				{ "application/vnd.geonext", new []{ "gxt" } },
				{ "application/vnd.geoplan", new []{ "g2w" } },
				{ "application/vnd.geospace", new []{ "g3w" } },
				{ "application/vnd.gmx", new []{ "gmx" } },
				{ "application/vnd.google-earth.kml+xml", new []{ "kml" } },
				{ "application/vnd.google-earth.kmz", new []{ "kmz" } },
				{ "application/vnd.grafeq", new []{ "gqf", "gqs" } },
				{ "application/vnd.groove-account", new []{ "gac" } },
				{ "application/vnd.groove-help", new []{ "ghf" } },
				{ "application/vnd.groove-identity-message", new []{ "gim" } },
				{ "application/vnd.groove-injector", new []{ "grv" } },
				{ "application/vnd.groove-tool-message", new []{ "gtm" } },
				{ "application/vnd.groove-tool-template", new []{ "tpl" } },
				{ "application/vnd.groove-vcard", new []{ "vcg" } },
				{ "application/vnd.hal+xml", new []{ "hal" } },
				{ "application/vnd.handheld-entertainment+xml", new []{ "zmm" } },
				{ "application/vnd.hbci", new []{ "hbci" } },
				{ "application/vnd.hhe.lesson-player", new []{ "les" } },
				{ "application/vnd.hp-hpgl", new []{ "hpgl" } },
				{ "application/vnd.hp-hpid", new []{ "hpid" } },
				{ "application/vnd.hp-hps", new []{ "hps" } },
				{ "application/vnd.hp-jlyt", new []{ "jlt" } },
				{ "application/vnd.hp-pcl", new []{ "pcl" } },
				{ "application/vnd.hp-pclxl", new []{ "pclxl" } },
				{ "application/vnd.hydrostatix.sof-data", new []{ "sfd-hdstx" } },
				{ "application/vnd.ibm.minipay", new []{ "mpy" } },
				{ "application/vnd.ibm.modcap", new []{ "afp", "listafp", "list3820" } },
				{ "application/vnd.ibm.rights-management", new []{ "irm" } },
				{ "application/vnd.ibm.secure-container", new []{ "sc" } },
				{ "application/vnd.iccprofile", new []{ "icc", "icm" } },
				{ "application/vnd.igloader", new []{ "igl" } },
				{ "application/vnd.immervision-ivp", new []{ "ivp" } },
				{ "application/vnd.immervision-ivu", new []{ "ivu" } },
				{ "application/vnd.insors.igm", new []{ "igm" } },
				{ "application/vnd.intercon.formnet", new []{ "xpw", "xpx" } },
				{ "application/vnd.intergeo", new []{ "i2g" } },
				{ "application/vnd.intu.qbo", new []{ "qbo" } },
				{ "application/vnd.intu.qfx", new []{ "qfx" } },
				{ "application/vnd.ipunplugged.rcprofile", new []{ "rcprofile" } },
				{ "application/vnd.irepository.package+xml", new []{ "irp" } },
				{ "application/vnd.is-xpr", new []{ "xpr" } },
				{ "application/vnd.isac.fcs", new []{ "fcs" } },
				{ "application/vnd.jam", new []{ "jam" } },
				{ "application/vnd.jcp.javame.midlet-rms", new []{ "rms" } },
				{ "application/vnd.jisp", new []{ "jisp" } },
				{ "application/vnd.joost.joda-archive", new []{ "joda" } },
				{ "application/vnd.kahootz", new []{ "ktz", "ktr" } },
				{ "application/vnd.kde.karbon", new []{ "karbon" } },
				{ "application/vnd.kde.kchart", new []{ "chrt" } },
				{ "application/vnd.kde.kformula", new []{ "kfo" } },
				{ "application/vnd.kde.kivio", new []{ "flw" } },
				{ "application/vnd.kde.kontour", new []{ "kon" } },
				{ "application/vnd.kde.kpresenter", new []{ "kpr", "kpt" } },
				{ "application/vnd.kde.kspread", new []{ "ksp" } },
				{ "application/vnd.kde.kword", new []{ "kwd", "kwt" } },
				{ "application/vnd.kenameaapp", new []{ "htke" } },
				{ "application/vnd.kidspiration", new []{ "kia" } },
				{ "application/vnd.kinar", new []{ "kne", "knp" } },
				{ "application/vnd.koan", new []{ "skp", "skd", "skt", "skm" } },
				{ "application/vnd.kodak-descriptor", new []{ "sse" } },
				{ "application/vnd.las.las+xml", new []{ "lasxml" } },
				{ "application/vnd.llamagraphics.life-balance.desktop", new []{ "lbd" } },
				{ "application/vnd.llamagraphics.life-balance.exchange+xml", new []{ "lbe" } },
				{ "application/vnd.lotus-1-2-3", new []{ "123" } },
				{ "application/vnd.lotus-approach", new []{ "apr" } },
				{ "application/vnd.lotus-freelance", new []{ "pre" } },
				{ "application/vnd.lotus-notes", new []{ "nsf" } },
				{ "application/vnd.lotus-organizer", new []{ "org" } },
				{ "application/vnd.lotus-screencam", new []{ "scm" } },
				{ "application/vnd.lotus-wordpro", new []{ "lwp" } },
				{ "application/vnd.macports.portpkg", new []{ "portpkg" } },
				{ "application/vnd.mcd", new []{ "mcd" } },
				{ "application/vnd.medcalcdata", new []{ "mc1" } },
				{ "application/vnd.mediastation.cdkey", new []{ "cdkey" } },
				{ "application/vnd.mfer", new []{ "mwf" } },
				{ "application/vnd.mfmp", new []{ "mfm" } },
				{ "application/vnd.micrografx.flo", new []{ "flo" } },
				{ "application/vnd.micrografx.igx", new []{ "igx" } },
				{ "application/vnd.mif", new []{ "mif" } },
				{ "application/vnd.mobius.daf", new []{ "daf" } },
				{ "application/vnd.mobius.dis", new []{ "dis" } },
				{ "application/vnd.mobius.mbk", new []{ "mbk" } },
				{ "application/vnd.mobius.mqy", new []{ "mqy" } },
				{ "application/vnd.mobius.msl", new []{ "msl" } },
				{ "application/vnd.mobius.plc", new []{ "plc" } },
				{ "application/vnd.mobius.txf", new []{ "txf" } },
				{ "application/vnd.mophun.application", new []{ "mpn" } },
				{ "application/vnd.mophun.certificate", new []{ "mpc" } },
				{ "application/vnd.mozilla.xul+xml", new []{ "xul" } },
				{ "application/vnd.ms-artgalry", new []{ "cil" } },
				{ "application/vnd.ms-cab-compressed", new []{ "cab" } },
				{ "application/vnd.ms-excel", new []{ "xls", "xlm", "xla", "xlc", "xlt", "xlw" } },
				{ "application/vnd.ms-excel.addin.macroenabled.12", new []{ "xlam" } },
				{ "application/vnd.ms-excel.sheet.binary.macroenabled.12", new []{ "xlsb" } },
				{ "application/vnd.ms-excel.sheet.macroenabled.12", new []{ "xlsm" } },
				{ "application/vnd.ms-excel.template.macroenabled.12", new []{ "xltm" } },
				{ "application/vnd.ms-fontobject", new []{ "eot" } },
				{ "application/vnd.ms-htmlhelp", new []{ "chm" } },
				{ "application/vnd.ms-ims", new []{ "ims" } },
				{ "application/vnd.ms-lrm", new []{ "lrm" } },
				{ "application/vnd.ms-officetheme", new []{ "thmx" } },
				{ "application/vnd.ms-pki.seccat", new []{ "cat" } },
				{ "application/vnd.ms-pki.stl", new []{ "stl" } },
				{ "application/vnd.ms-powerpoint", new []{ "ppt", "pps", "pot" } },
				{ "application/vnd.ms-powerpoint.addin.macroenabled.12", new []{ "ppam" } },
				{ "application/vnd.ms-powerpoint.presentation.macroenabled.12", new []{ "pptm" } },
				{ "application/vnd.ms-powerpoint.slide.macroenabled.12", new []{ "sldm" } },
				{ "application/vnd.ms-powerpoint.slideshow.macroenabled.12", new []{ "ppsm" } },
				{ "application/vnd.ms-powerpoint.template.macroenabled.12", new []{ "potm" } },
				{ "application/vnd.ms-project", new []{ "mpp", "mpt" } },
				{ "application/vnd.ms-word.document.macroenabled.12", new []{ "docm" } },
				{ "application/vnd.ms-word.template.macroenabled.12", new []{ "dotm" } },
				{ "application/vnd.ms-works", new []{ "wps", "wks", "wcm", "wdb" } },
				{ "application/vnd.ms-wpl", new []{ "wpl" } },
				{ "application/vnd.ms-xpsdocument", new []{ "xps" } },
				{ "application/vnd.mseq", new []{ "mseq" } },
				{ "application/vnd.musician", new []{ "mus" } },
				{ "application/vnd.muvee.style", new []{ "msty" } },
				{ "application/vnd.mynfc", new []{ "taglet" } },
				{ "application/vnd.neurolanguage.nlu", new []{ "nlu" } },
				{ "application/vnd.nitf", new []{ "ntf", "nitf" } },
				{ "application/vnd.noblenet-directory", new []{ "nnd" } },
				{ "application/vnd.noblenet-sealer", new []{ "nns" } },
				{ "application/vnd.noblenet-web", new []{ "nnw" } },
				{ "application/vnd.nokia.n-gage.data", new []{ "ngdat" } },
				{ "application/vnd.nokia.n-gage.symbian.install", new []{ "n-gage" } },
				{ "application/vnd.nokia.radio-preset", new []{ "rpst" } },
				{ "application/vnd.nokia.radio-presets", new []{ "rpss" } },
				{ "application/vnd.novadigm.edm", new []{ "edm" } },
				{ "application/vnd.novadigm.edx", new []{ "edx" } },
				{ "application/vnd.novadigm.ext", new []{ "ext" } },
				{ "application/vnd.oasis.opendocument.chart", new []{ "odc" } },
				{ "application/vnd.oasis.opendocument.chart-template", new []{ "otc" } },
				{ "application/vnd.oasis.opendocument.database", new []{ "odb" } },
				{ "application/vnd.oasis.opendocument.formula", new []{ "odf" } },
				{ "application/vnd.oasis.opendocument.formula-template", new []{ "odft" } },
				{ "application/vnd.oasis.opendocument.graphics", new []{ "odg" } },
				{ "application/vnd.oasis.opendocument.graphics-template", new []{ "otg" } },
				{ "application/vnd.oasis.opendocument.image", new []{ "odi" } },
				{ "application/vnd.oasis.opendocument.image-template", new []{ "oti" } },
				{ "application/vnd.oasis.opendocument.presentation", new []{ "odp" } },
				{ "application/vnd.oasis.opendocument.presentation-template", new []{ "otp" } },
				{ "application/vnd.oasis.opendocument.spreadsheet", new []{ "ods" } },
				{ "application/vnd.oasis.opendocument.spreadsheet-template", new []{ "ots" } },
				{ "application/vnd.oasis.opendocument.text", new []{ "odt" } },
				{ "application/vnd.oasis.opendocument.text-master", new []{ "odm" } },
				{ "application/vnd.oasis.opendocument.text-template", new []{ "ott" } },
				{ "application/vnd.oasis.opendocument.text-web", new []{ "oth" } },
				{ "application/vnd.olpc-sugar", new []{ "xo" } },
				{ "application/vnd.oma.dd2+xml", new []{ "dd2" } },
				{ "application/vnd.openofficeorg.extension", new []{ "oxt" } },
				{ "application/vnd.openxmlformats-officedocument.presentationml.presentation", new []{ "pptx" } },
				{ "application/vnd.openxmlformats-officedocument.presentationml.slide", new []{ "sldx" } },
				{ "application/vnd.openxmlformats-officedocument.presentationml.slideshow", new []{ "ppsx" } },
				{ "application/vnd.openxmlformats-officedocument.presentationml.template", new []{ "potx" } },
				{ "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", new []{ "xlsx" } },
				{ "application/vnd.openxmlformats-officedocument.spreadsheetml.template", new []{ "xltx" } },
				{ "application/vnd.openxmlformats-officedocument.wordprocessingml.document", new []{ "docx" } },
				{ "application/vnd.openxmlformats-officedocument.wordprocessingml.template", new []{ "dotx" } },
				{ "application/vnd.osgeo.mapguide.package", new []{ "mgp" } },
				{ "application/vnd.osgi.dp", new []{ "dp" } },
				{ "application/vnd.osgi.subsystem", new []{ "esa" } },
				{ "application/vnd.palm", new []{ "pdb", "pqa", "oprc" } },
				{ "application/vnd.pawaafile", new []{ "paw" } },
				{ "application/vnd.pg.format", new []{ "str" } },
				{ "application/vnd.pg.osasli", new []{ "ei6" } },
				{ "application/vnd.picsel", new []{ "efif" } },
				{ "application/vnd.pmi.widget", new []{ "wg" } },
				{ "application/vnd.pocketlearn", new []{ "plf" } },
				{ "application/vnd.powerbuilder6", new []{ "pbd" } },
				{ "application/vnd.previewsystems.box", new []{ "box" } },
				{ "application/vnd.proteus.magazine", new []{ "mgz" } },
				{ "application/vnd.publishare-delta-tree", new []{ "qps" } },
				{ "application/vnd.pvi.ptid1", new []{ "ptid" } },
				{ "application/vnd.quark.quarkxpress", new []{ "qxd", "qxt", "qwd", "qwt", "qxl", "qxb" } },
				{ "application/vnd.realvnc.bed", new []{ "bed" } },
				{ "application/vnd.recordare.musicxml", new []{ "mxl" } },
				{ "application/vnd.recordare.musicxml+xml", new []{ "musicxml" } },
				{ "application/vnd.rig.cryptonote", new []{ "cryptonote" } },
				{ "application/vnd.rim.cod", new []{ "cod" } },
				{ "application/vnd.rn-realmedia", new []{ "rm" } },
				{ "application/vnd.rn-realmedia-vbr", new []{ "rmvb" } },
				{ "application/vnd.route66.link66+xml", new []{ "link66" } },
				{ "application/vnd.sailingtracker.track", new []{ "st" } },
				{ "application/vnd.seemail", new []{ "see" } },
				{ "application/vnd.sema", new []{ "sema" } },
				{ "application/vnd.semd", new []{ "semd" } },
				{ "application/vnd.semf", new []{ "semf" } },
				{ "application/vnd.shana.informed.formdata", new []{ "ifm" } },
				{ "application/vnd.shana.informed.formtemplate", new []{ "itp" } },
				{ "application/vnd.shana.informed.interchange", new []{ "iif" } },
				{ "application/vnd.shana.informed.package", new []{ "ipk" } },
				{ "application/vnd.simtech-mindmapper", new []{ "twd", "twds" } },
				{ "application/vnd.smaf", new []{ "mmf" } },
				{ "application/vnd.smart.teacher", new []{ "teacher" } },
				{ "application/vnd.solent.sdkm+xml", new []{ "sdkm", "sdkd" } },
				{ "application/vnd.spotfire.dxp", new []{ "dxp" } },
				{ "application/vnd.spotfire.sfs", new []{ "sfs" } },
				{ "application/vnd.stardivision.calc", new []{ "sdc" } },
				{ "application/vnd.stardivision.draw", new []{ "sda" } },
				{ "application/vnd.stardivision.impress", new []{ "sdd" } },
				{ "application/vnd.stardivision.math", new []{ "smf" } },
				{ "application/vnd.stardivision.writer", new []{ "sdw", "vor" } },
				{ "application/vnd.stardivision.writer-global", new []{ "sgl" } },
				{ "application/vnd.stepmania.package", new []{ "smzip" } },
				{ "application/vnd.stepmania.stepchart", new []{ "sm" } },
				{ "application/vnd.sun.xml.calc", new []{ "sxc" } },
				{ "application/vnd.sun.xml.calc.template", new []{ "stc" } },
				{ "application/vnd.sun.xml.draw", new []{ "sxd" } },
				{ "application/vnd.sun.xml.draw.template", new []{ "std" } },
				{ "application/vnd.sun.xml.impress", new []{ "sxi" } },
				{ "application/vnd.sun.xml.impress.template", new []{ "sti" } },
				{ "application/vnd.sun.xml.math", new []{ "sxm" } },
				{ "application/vnd.sun.xml.writer", new []{ "sxw" } },
				{ "application/vnd.sun.xml.writer.global", new []{ "sxg" } },
				{ "application/vnd.sun.xml.writer.template", new []{ "stw" } },
				{ "application/vnd.sus-calendar", new []{ "sus", "susp" } },
				{ "application/vnd.svd", new []{ "svd" } },
				{ "application/vnd.symbian.install", new []{ "sis", "sisx" } },
				{ "application/vnd.syncml+xml", new []{ "xsm" } },
				{ "application/vnd.syncml.dm+wbxml", new []{ "bdm" } },
				{ "application/vnd.syncml.dm+xml", new []{ "xdm" } },
				{ "application/vnd.tao.intent-module-archive", new []{ "tao" } },
				{ "application/vnd.tcpdump.pcap", new []{ "pcap", "cap", "dmp" } },
				{ "application/vnd.tmobile-livetv", new []{ "tmo" } },
				{ "application/vnd.trid.tpt", new []{ "tpt" } },
				{ "application/vnd.triscape.mxs", new []{ "mxs" } },
				{ "application/vnd.trueapp", new []{ "tra" } },
				{ "application/vnd.ufdl", new []{ "ufd", "ufdl" } },
				{ "application/vnd.uiq.theme", new []{ "utz" } },
				{ "application/vnd.umajin", new []{ "umj" } },
				{ "application/vnd.unity", new []{ "unityweb" } },
				{ "application/vnd.uoml+xml", new []{ "uoml" } },
				{ "application/vnd.vcx", new []{ "vcx" } },
				{ "application/vnd.visio", new []{ "vsd", "vst", "vss", "vsw" } },
				{ "application/vnd.visionary", new []{ "vis" } },
				{ "application/vnd.vsf", new []{ "vsf" } },
				{ "application/vnd.wap.wbxml", new []{ "wbxml" } },
				{ "application/vnd.wap.wmlc", new []{ "wmlc" } },
				{ "application/vnd.wap.wmlscriptc", new []{ "wmlsc" } },
				{ "application/vnd.webturbo", new []{ "wtb" } },
				{ "application/vnd.wolfram.player", new []{ "nbp" } },
				{ "application/vnd.wordperfect", new []{ "wpd" } },
				{ "application/vnd.wqd", new []{ "wqd" } },
				{ "application/vnd.wt.stf", new []{ "stf" } },
				{ "application/vnd.xara", new []{ "xar" } },
				{ "application/vnd.xfdl", new []{ "xfdl" } },
				{ "application/vnd.yamaha.hv-dic", new []{ "hvd" } },
				{ "application/vnd.yamaha.hv-script", new []{ "hvs" } },
				{ "application/vnd.yamaha.hv-voice", new []{ "hvp" } },
				{ "application/vnd.yamaha.openscoreformat", new []{ "osf" } },
				{ "application/vnd.yamaha.openscoreformat.osfpvg+xml", new []{ "osfpvg" } },
				{ "application/vnd.yamaha.smaf-audio", new []{ "saf" } },
				{ "application/vnd.yamaha.smaf-phrase", new []{ "spf" } },
				{ "application/vnd.yellowriver-custom-menu", new []{ "cmp" } },
				{ "application/vnd.zul", new []{ "zir", "zirz" } },
				{ "application/vnd.zzazz.deck+xml", new []{ "zaz" } },
				{ "application/voicexml+xml", new []{ "vxml" } },
				{ "application/widget", new []{ "wgt" } },
				{ "application/winhlp", new []{ "hlp" } },
				{ "application/wsdl+xml", new []{ "wsdl" } },
				{ "application/wspolicy+xml", new []{ "wspolicy" } },
				{ "application/x-7z-compressed", new []{ "7z" } },
				{ "application/x-abiword", new []{ "abw" } },
				{ "application/x-ace-compressed", new []{ "ace" } },
				{ "application/x-apple-diskimage", new []{ "dmg" } },
				{ "application/x-authorware-bin", new []{ "aab", "x32", "u32", "vox" } },
				{ "application/x-authorware-map", new []{ "aam" } },
				{ "application/x-authorware-seg", new []{ "aas" } },
				{ "application/x-bcpio", new []{ "bcpio" } },
				{ "application/x-bittorrent", new []{ "torrent" } },
				{ "application/x-blorb", new []{ "blb", "blorb" } },
				{ "application/x-bzip", new []{ "bz" } },
				{ "application/x-bzip2", new []{ "bz2", "boz" } },
				{ "application/x-cbr", new []{ "cbr", "cba", "cbt", "cbz", "cb7" } },
				{ "application/x-cdlink", new []{ "vcd" } },
				{ "application/x-cfs-compressed", new []{ "cfs" } },
				{ "application/x-chat", new []{ "chat" } },
				{ "application/x-chess-pgn", new []{ "pgn" } },
				{ "application/x-conference", new []{ "nsc" } },
				{ "application/x-cpio", new []{ "cpio" } },
				{ "application/x-csh", new []{ "csh" } },
				{ "application/x-debian-package", new []{ "deb", "udeb" } },
				{ "application/x-dgc-compressed", new []{ "dgc" } },
				{ "application/x-director", new []{ "dir", "dcr", "dxr", "cst", "cct", "cxt", "w3d", "fgd", "swa" } },
				{ "application/x-doom", new []{ "wad" } },
				{ "application/x-dtbncx+xml", new []{ "ncx" } },
				{ "application/x-dtbook+xml", new []{ "dtb" } },
				{ "application/x-dtbresource+xml", new []{ "res" } },
				{ "application/x-dvi", new []{ "dvi" } },
				{ "application/x-envoy", new []{ "evy" } },
				{ "application/x-eva", new []{ "eva" } },
				{ "application/x-font-bdf", new []{ "bdf" } },
				{ "application/x-font-ghostscript", new []{ "gsf" } },
				{ "application/x-font-linux-psf", new []{ "psf" } },
				{ "application/x-font-pcf", new []{ "pcf" } },
				{ "application/x-font-snf", new []{ "snf" } },
				{ "application/x-font-type1", new []{ "pfa", "pfb", "pfm", "afm" } },
				{ "application/x-freearc", new []{ "arc" } },
				{ "application/x-futuresplash", new []{ "spl" } },
				{ "application/x-gca-compressed", new []{ "gca" } },
				{ "application/x-glulx", new []{ "ulx" } },
				{ "application/x-gnumeric", new []{ "gnumeric" } },
				{ "application/x-gramps-xml", new []{ "gramps" } },
				{ "application/x-gtar", new []{ "gtar" } },
				{ "application/x-hdf", new []{ "hdf" } },
				{ "application/x-install-instructions", new []{ "install" } },
				{ "application/x-iso9660-image", new []{ "iso" } },
				{ "application/x-java-jnlp-file", new []{ "jnlp" } },
				{ "application/x-latex", new []{ "latex" } },
				{ "application/x-lzh-compressed", new []{ "lzh", "lha" } },
				{ "application/x-mie", new []{ "mie" } },
				{ "application/x-mobipocket-ebook", new []{ "prc", "mobi" } },
				{ "application/x-ms-application", new []{ "application" } },
				{ "application/x-ms-shortcut", new []{ "lnk" } },
				{ "application/x-ms-wmd", new []{ "wmd" } },
				{ "application/x-ms-wmz", new []{ "wmz" } },
				{ "application/x-ms-xbap", new []{ "xbap" } },
				{ "application/x-msaccess", new []{ "mdb" } },
				{ "application/x-msbinder", new []{ "obd" } },
				{ "application/x-mscardfile", new []{ "crd" } },
				{ "application/x-msclip", new []{ "clp" } },
				{ "application/x-msdownload", new []{ "exe", "dll", "com", "bat", "msi" } },
				{ "application/x-msmediaview", new []{ "mvb", "m13", "m14" } },
				{ "application/x-msmetafile", new []{ "wmf", "wmz", "emf", "emz" } },
				{ "application/x-msmoney", new []{ "mny" } },
				{ "application/x-mspublisher", new []{ "pub" } },
				{ "application/x-msschedule", new []{ "scd" } },
				{ "application/x-msterminal", new []{ "trm" } },
				{ "application/x-mswrite", new []{ "wri" } },
				{ "application/x-netcdf", new []{ "nc", "cdf" } },
				{ "application/x-nzb", new []{ "nzb" } },
				{ "application/x-pkcs12", new []{ "p12", "pfx" } },
				{ "application/x-pkcs7-certificates", new []{ "p7b", "spc" } },
				{ "application/x-pkcs7-certreqresp", new []{ "p7r" } },
				{ "application/x-rar-compressed", new []{ "rar" } },
				{ "application/x-research-info-systems", new []{ "ris" } },
				{ "application/x-sh", new []{ "sh" } },
				{ "application/x-shar", new []{ "shar" } },
				{ "application/x-shockwave-flash", new []{ "swf" } },
				{ "application/x-silverlight-app", new []{ "xap" } },
				{ "application/x-sql", new []{ "sql" } },
				{ "application/x-stuffit", new []{ "sit" } },
				{ "application/x-stuffitx", new []{ "sitx" } },
				{ "application/x-subrip", new []{ "srt" } },
				{ "application/x-sv4cpio", new []{ "sv4cpio" } },
				{ "application/x-sv4crc", new []{ "sv4crc" } },
				{ "application/x-t3vm-image", new []{ "t3" } },
				{ "application/x-tads", new []{ "gam" } },
				{ "application/x-tar", new []{ "tar" } },
				{ "application/x-tcl", new []{ "tcl" } },
				{ "application/x-tex", new []{ "tex" } },
				{ "application/x-tex-tfm", new []{ "tfm" } },
				{ "application/x-texinfo", new []{ "texinfo", "texi" } },
				{ "application/x-tgif", new []{ "obj" } },
				{ "application/x-ustar", new []{ "ustar" } },
				{ "application/x-wais-source", new []{ "src" } },
				{ "application/x-x509-ca-cert", new []{ "der", "crt" } },
				{ "application/x-xfig", new []{ "fig" } },
				{ "application/x-xliff+xml", new []{ "xlf" } },
				{ "application/x-xpinstall", new []{ "xpi" } },
				{ "application/x-xz", new []{ "xz" } },
				{ "application/x-zmachine", new []{ "z1", "z2", "z3", "z4", "z5", "z6", "z7", "z8" } },
				{ "application/xaml+xml", new []{ "xaml" } },
				{ "application/xcap-diff+xml", new []{ "xdf" } },
				{ "application/xenc+xml", new []{ "xenc" } },
				{ "application/xhtml+xml", new []{ "xhtml", "xht" } },
				{ "application/xml", new []{ "xml", "xsl" } },
				{ "application/xml-dtd", new []{ "dtd" } },
				{ "application/xop+xml", new []{ "xop" } },
				{ "application/xproc+xml", new []{ "xpl" } },
				{ "application/xslt+xml", new []{ "xslt" } },
				{ "application/xspf+xml", new []{ "xspf" } },
				{ "application/xv+xml", new []{ "mxml", "xhvml", "xvml", "xvm" } },
				{ "application/yang", new []{ "yang" } },
				{ "application/yin+xml", new []{ "yin" } },
				{ "application/zip", new []{ "zip" } },
				{ "audio/adpcm", new []{ "adp" } },
				{ "audio/basic", new []{ "au", "snd" } },
				{ "audio/midi", new []{ "mid", "midi", "kar", "rmi" } },
				{ "audio/mp4", new []{ "m4a", "mp4a" } },
				{ "audio/mpeg", new []{ "mpga", "mp2", "mp2a", "mp3", "m2a", "m3a" } },
				{ "audio/ogg", new []{ "oga", "ogg", "spx" } },
				{ "audio/s3m", new []{ "s3m" } },
				{ "audio/silk", new []{ "sil" } },
				{ "audio/vnd.dece.audio", new []{ "uva", "uvva" } },
				{ "audio/vnd.digital-winds", new []{ "eol" } },
				{ "audio/vnd.dra", new []{ "dra" } },
				{ "audio/vnd.dts", new []{ "dts" } },
				{ "audio/vnd.dts.hd", new []{ "dtshd" } },
				{ "audio/vnd.lucent.voice", new []{ "lvp" } },
				{ "audio/vnd.ms-playready.media.pya", new []{ "pya" } },
				{ "audio/vnd.nuera.ecelp4800", new []{ "ecelp4800" } },
				{ "audio/vnd.nuera.ecelp7470", new []{ "ecelp7470" } },
				{ "audio/vnd.nuera.ecelp9600", new []{ "ecelp9600" } },
				{ "audio/vnd.rip", new []{ "rip" } },
				{ "audio/webm", new []{ "weba" } },
				{ "audio/x-aac", new []{ "aac" } },
				{ "audio/x-aiff", new []{ "aif", "aiff", "aifc" } },
				{ "audio/x-caf", new []{ "caf" } },
				{ "audio/x-flac", new []{ "flac" } },
				{ "audio/x-matroska", new []{ "mka" } },
				{ "audio/x-mpegurl", new []{ "m3u" } },
				{ "audio/x-ms-wax", new []{ "wax" } },
				{ "audio/x-ms-wma", new []{ "wma" } },
				{ "audio/x-pn-realaudio", new []{ "ram", "ra" } },
				{ "audio/x-pn-realaudio-plugin", new []{ "rmp" } },
				{ "audio/x-wav", new []{ "wav" } },
				{ "audio/xm", new []{ "xm" } },
				{ "chemical/x-cdx", new []{ "cdx" } },
				{ "chemical/x-cif", new []{ "cif" } },
				{ "chemical/x-cmdf", new []{ "cmdf" } },
				{ "chemical/x-cml", new []{ "cml" } },
				{ "chemical/x-csml", new []{ "csml" } },
				{ "chemical/x-xyz", new []{ "xyz" } },
				{ "font/collection", new []{ "ttc" } },
				{ "font/otf", new []{ "otf" } },
				{ "font/ttf", new []{ "ttf" } },
				{ "font/woff", new []{ "woff" } },
				{ "font/woff2", new []{ "woff2" } },
				{ "image/bmp", new []{ "bmp" } },
				{ "image/cgm", new []{ "cgm" } },
				{ "image/g3fax", new []{ "g3" } },
				{ "image/gif", new []{ "gif" } },
				{ "image/ief", new []{ "ief" } },
				{ "image/jpeg", new []{ "jpeg", "jpg", "jpe" } },
				{ "image/ktx", new []{ "ktx" } },
				{ "image/png", new []{ "png" } },
				{ "image/prs.btif", new []{ "btif" } },
				{ "image/sgi", new []{ "sgi" } },
				{ "image/svg+xml", new []{ "svg", "svgz" } },
				{ "image/tiff", new []{ "tiff", "tif" } },
				{ "image/vnd.adobe.photoshop", new []{ "psd" } },
				{ "image/vnd.dece.graphic", new []{ "uvi", "uvvi", "uvg", "uvvg" } },
				{ "image/vnd.djvu", new []{ "djvu", "djv" } },
				{ "image/vnd.dvb.subtitle", new []{ "sub" } },
				{ "image/vnd.dwg", new []{ "dwg" } },
				{ "image/vnd.dxf", new []{ "dxf" } },
				{ "image/vnd.fastbidsheet", new []{ "fbs" } },
				{ "image/vnd.fpx", new []{ "fpx" } },
				{ "image/vnd.fst", new []{ "fst" } },
				{ "image/vnd.fujixerox.edmics-mmr", new []{ "mmr" } },
				{ "image/vnd.fujixerox.edmics-rlc", new []{ "rlc" } },
				{ "image/vnd.ms-modi", new []{ "mdi" } },
				{ "image/vnd.ms-photo", new []{ "wdp" } },
				{ "image/vnd.net-fpx", new []{ "npx" } },
				{ "image/vnd.wap.wbmp", new []{ "wbmp" } },
				{ "image/vnd.xiff", new []{ "xif" } },
				{ "image/webp", new []{ "webp" } },
				{ "image/x-3ds", new []{ "3ds" } },
				{ "image/x-cmu-raster", new []{ "ras" } },
				{ "image/x-cmx", new []{ "cmx" } },
				{ "image/x-freehand", new []{ "fh", "fhc", "fh4", "fh5", "fh7" } },
				{ "image/x-icon", new []{ "ico" } },
				{ "image/x-mrsid-image", new []{ "sid" } },
				{ "image/x-pcx", new []{ "pcx" } },
				{ "image/x-pict", new []{ "pic", "pct" } },
				{ "image/x-portable-anymap", new []{ "pnm" } },
				{ "image/x-portable-bitmap", new []{ "pbm" } },
				{ "image/x-portable-graymap", new []{ "pgm" } },
				{ "image/x-portable-pixmap", new []{ "ppm" } },
				{ "image/x-rgb", new []{ "rgb" } },
				{ "image/x-tga", new []{ "tga" } },
				{ "image/x-xbitmap", new []{ "xbm" } },
				{ "image/x-xpixmap", new []{ "xpm" } },
				{ "image/x-xwindowdump", new []{ "xwd" } },
				{ "message/rfc822", new []{ "eml", "mime" } },
				{ "model/iges", new []{ "igs", "iges" } },
				{ "model/mesh", new []{ "msh", "mesh", "silo" } },
				{ "model/vnd.collada+xml", new []{ "dae" } },
				{ "model/vnd.dwf", new []{ "dwf" } },
				{ "model/vnd.gdl", new []{ "gdl" } },
				{ "model/vnd.gtw", new []{ "gtw" } },
				{ "model/vnd.mts", new []{ "mts" } },
				{ "model/vnd.vtu", new []{ "vtu" } },
				{ "model/vrml", new []{ "wrl", "vrml" } },
				{ "model/x3d+binary", new []{ "x3db", "x3dbz" } },
				{ "model/x3d+vrml", new []{ "x3dv", "x3dvz" } },
				{ "model/x3d+xml", new []{ "x3d", "x3dz" } },
				{ "text/cache-manifest", new []{ "appcache" } },
				{ "text/calendar", new []{ "ics", "ifb" } },
				{ "text/css", new []{ "css" } },
				{ "text/csv", new []{ "csv" } },
				{ "text/html", new []{ "html", "htm" } },
				{ "text/n3", new []{ "n3" } },
				{ "text/plain", new []{ "txt", "text", "conf", "def", "list", "log", "in" } },
				{ "text/prs.lines.tag", new []{ "dsc" } },
				{ "text/richtext", new []{ "rtx" } },
				{ "text/sgml", new []{ "sgml", "sgm" } },
				{ "text/tab-separated-values", new []{ "tsv" } },
				{ "text/troff", new []{ "t", "tr", "roff", "man", "me", "ms" } },
				{ "text/turtle", new []{ "ttl" } },
				{ "text/uri-list", new []{ "uri", "uris", "urls" } },
				{ "text/vcard", new []{ "vcard" } },
				{ "text/vnd.curl", new []{ "curl" } },
				{ "text/vnd.curl.dcurl", new []{ "dcurl" } },
				{ "text/vnd.curl.mcurl", new []{ "mcurl" } },
				{ "text/vnd.curl.scurl", new []{ "scurl" } },
				{ "text/vnd.dvb.subtitle", new []{ "sub" } },
				{ "text/vnd.fly", new []{ "fly" } },
				{ "text/vnd.fmi.flexstor", new []{ "flx" } },
				{ "text/vnd.graphviz", new []{ "gv" } },
				{ "text/vnd.in3d.3dml", new []{ "3dml" } },
				{ "text/vnd.in3d.spot", new []{ "spot" } },
				{ "text/vnd.sun.j2me.app-descriptor", new []{ "jad" } },
				{ "text/vnd.wap.wml", new []{ "wml" } },
				{ "text/vnd.wap.wmlscript", new []{ "wmls" } },
				{ "text/x-asm", new []{ "s", "asm" } },
				{ "text/x-c", new []{ "c", "cc", "cxx", "cpp", "h", "hh", "dic" } },
				{ "text/x-fortran", new []{ "f", "for", "f77", "f90" } },
				{ "text/x-java-source", new []{ "java" } },
				{ "text/x-nfo", new []{ "nfo" } },
				{ "text/x-opml", new []{ "opml" } },
				{ "text/x-pascal", new []{ "p", "pas" } },
				{ "text/x-setext", new []{ "etx" } },
				{ "text/x-sfv", new []{ "sfv" } },
				{ "text/x-uuencode", new []{ "uu" } },
				{ "text/x-vcalendar", new []{ "vcs" } },
				{ "text/x-vcard", new []{ "vcf" } },
				{ "video/3gpp", new []{ "3gp" } },
				{ "video/3gpp2", new []{ "3g2" } },
				{ "video/h261", new []{ "h261" } },
				{ "video/h263", new []{ "h263" } },
				{ "video/h264", new []{ "h264" } },
				{ "video/jpeg", new []{ "jpgv" } },
				{ "video/jpm", new []{ "jpm", "jpgm" } },
				{ "video/mj2", new []{ "mj2", "mjp2" } },
				{ "video/mp4", new []{ "mp4", "mp4v", "mpg4" } },
				{ "video/mpeg", new []{ "mpeg", "mpg", "mpe", "m1v", "m2v" } },
				{ "video/ogg", new []{ "ogv" } },
				{ "video/quicktime", new []{ "qt", "mov" } },
				{ "video/vnd.dece.hd", new []{ "uvh", "uvvh" } },
				{ "video/vnd.dece.mobile", new []{ "uvm", "uvvm" } },
				{ "video/vnd.dece.pd", new []{ "uvp", "uvvp" } },
				{ "video/vnd.dece.sd", new []{ "uvs", "uvvs" } },
				{ "video/vnd.dece.video", new []{ "uvv", "uvvv" } },
				{ "video/vnd.dvb.file", new []{ "dvb" } },
				{ "video/vnd.fvt", new []{ "fvt" } },
				{ "video/vnd.mpegurl", new []{ "mxu", "m4u" } },
				{ "video/vnd.ms-playready.media.pyv", new []{ "pyv" } },
				{ "video/vnd.uvvu.mp4", new []{ "uvu", "uvvu" } },
				{ "video/vnd.vivo", new []{ "viv" } },
				{ "video/webm", new []{ "webm" } },
				{ "video/x-f4v", new []{ "f4v" } },
				{ "video/x-fli", new []{ "fli" } },
				{ "video/x-flv", new []{ "flv" } },
				{ "video/x-m4v", new []{ "m4v" } },
				{ "video/x-matroska", new []{ "mkv", "mk3d", "mks" } },
				{ "video/x-mng", new []{ "mng" } },
				{ "video/x-ms-asf", new []{ "asf", "asx" } },
				{ "video/x-ms-vob", new []{ "vob" } },
				{ "video/x-ms-wm", new []{ "wm" } },
				{ "video/x-ms-wmv", new []{ "wmv" } },
				{ "video/x-ms-wmx", new []{ "wmx" } },
				{ "video/x-ms-wvx", new []{ "wvx" } },
				{ "video/x-msvideo", new []{ "avi" } },
				{ "video/x-sgi-movie", new []{ "movie" } },
				{ "video/x-smv", new []{ "smv" } },
				{ "x-conference/x-cooltalk", new []{ "ice" } },
            });

        public static string ComputeMimeType(string fileName)
        {
            var ext = ExtractExtension(fileName);
            var mime = _mimeTypes.Value.SingleOrDefault(m => m.Value.Contains(ext));
            
            return mime.Key == null ? DEFAULT_MIMETYPE : mime.Key;
        }

        public static string ExtractExtension(string fileName)
        {
            string ext = Path.GetExtension(fileName)?.Trim();

            if (string.IsNullOrEmpty(ext))
            {
                return string.Empty;
            }

            return ext.Substring(1).ToLower();
        }
    }
}
